return {
	Coin = {
		DisplayName = "2x Coins",
		Icon = "🪙",
		InventoryAttribute = "CoinBoosts",
		ActiveUntilAttribute = "ActiveCoinBoostUntil",
		Duration = 10 * 60,
		Multiplier = 2,
	},
	PetXP = {
		DisplayName = "2x Pet XP",
		Icon = "🧪",
		InventoryAttribute = "PetXPBoosts",
		ActiveUntilAttribute = "ActivePetXPBoostUntil",
		Duration = 10 * 60,
		Multiplier = 2,
	},
	Luck = {
		DisplayName = "2x Luck",
		Icon = "🍀",
		InventoryAttribute = "LuckBoosts",
		ActiveUntilAttribute = "ActiveLuckBoostUntil",
		Duration = 5 * 60,
		Multiplier = 2,
	},
}
