return {
	Rewards = {
		[1] = {
			Type = "Coins",
			Amount = 500,
			Display = "500 Coins",
		},
		[2] = {
			Type = "Coins",
			Amount = 750,
			Display = "750 Coins",
		},
		[3] = {
			Type = "LuckBoost",
			Amount = 1,
			Display = "Luck Boost",
		},
		[4] = {
			Type = "Coins",
			Amount = 1500,
			Display = "1,500 Coins",
		},
		[5] = {
			Type = "PetXPPotion",
			Amount = 1,
			Display = "Pet XP Potion",
		},
		[6] = {
			Type = "Egg",
			EggId = "Starter",
			Display = "Starter Egg",
		},
		[7] = {
			Type = "Pet",
			PetId = "LavaDragon",
			Display = "Lava Dragon",
		},
	},
}
